app/forms/teacher_forms.py
from flask_wtf import FlaskForm
from wtforms.validators import ValidationError
from wtforms import StringField, FloatField, BooleanField, TextAreaField, SubmitField, SelectField
from wtforms.fields import DateField, TimeField
from wtforms.widgets.html5 import DateInput, TimeInput, NumberInput
from wtforms.validators import DataRequired, Optional
import datetime
from ..app import app, db
from ..db.models import Student

with app.app_context():
	students = db.session.query(Student).all()
	student_choices = [(str(student.id), f'{student.preferred} {student.surname}') for student in students]
class TestForm(FlaskForm):
	name = StringField('Name', validators=[DataRequired()])
	time = FloatField('Time (minutes)', validators=[DataRequired()], widget=NumberInput(min=0))
	open_note = SelectField('Open Note', choices=[
		(True, 'Yes'),
		(False, 'No')
	],
	coerce=lambda x: x == 'True' if isinstance(x, str) else bool(x))
	comments = TextAreaField('Comments', validators=[Optional()], render_kw={'placeholder': 'Write any test instructions here...'})
	
	def validate_time(self, field):
		if field.data <= 0:
			raise ValidationError('Time must be greater than 0.')
		
class StudentTestForm(FlaskForm):
	# student_id = SelectField('Student', validators=[DataRequired()], 
	# 					 choices=student_choices,
	# 					)
	student_id = StringField('Student', validators=[DataRequired()])
	date = DateField('Date', format='%Y-%m-%d', validators=[DataRequired()], widget=DateInput(),
				  render_kw={
                                          'min': datetime.datetime.now().strftime("%Y-%m-%d")
				  })
	time = TimeField('Time', validators=[DataRequired()], widget=TimeInput(),
				  render_kw={
										  'min': datetime.time(hour=8, minute=15),
										  'max': datetime.time(hour=17, minute=30),
				  })
	comments = TextAreaField('Comments', validators=[Optional()])
	submit = SubmitField('Submit')

	def iter_choices(self):
		# This method is used to iterate over the choices for the student_id field
		return student_choices

app/blueprints/teacher.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
import datetime
from ..forms.teacher_forms import TestForm, StudentTestForm
from ..db.models import Test, Teacher, StudentTest, Student
from ..app import app, db

bp = Blueprint('teacher', __name__, url_prefix='/tests')


@bp.route('/create_test', methods=['GET', 'POST'])
def create_test():
    TEACHER = db.session.query(Teacher).where(Teacher.id == 1).first()
    form = TestForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            # Extract form data
            name = form.name.data.lower()
            time = form.time.data
            open_note = form.open_note.data
            comments = form.comments.data
            # check if it already exists
            existing_test = Test.query.filter_by(name=name, teacher_id=TEACHER.id).first()
            if existing_test:
                flash('You have already created a test with this name', 'error')
                return render_template('teacher/create_test.html', form=form)
            # Create and save the Test object
            test = Test(name=name, time=time, open_note=open_note, comments=comments, teacher=TEACHER)
        
            db.session.add(test)
            db.session.commit()
            flash('Test created successfully!', 'success')
            return redirect(url_for('teacher.edit_test', test_id=test.id))
        else:
            flash(form.errors, 'error')

    return render_template('teacher/create_test.html', form=form)

@bp.route('/')
def get_tests():
    TEACHER = db.session.query(Teacher).where(Teacher.id == 1).first()
    tests = db.session.query(Test).filter(Test.teacher == TEACHER).all()
    return render_template('teacher/tests.html', tests=tests)

@bp.route('/edit/<int:test_id>', methods=['GET', 'POST'])
def edit_test(test_id):
    TEACHER = db.session.query(Teacher).where(Teacher.id == 1).first()
    # Fetch the test by ID and ensure the teacher owns the test
    test = db.session.query(Test).filter(Test.id == test_id, Test.teacher_id == TEACHER.id).first()
    if not test:
        flash("Test not found or you do not have permission to edit this test", 'error')
        return redirect(url_for('teacher.get_tests'))

    enrolled_students = db.session.query(StudentTest).filter(StudentTest.test_id == test_id).all()
    # Create a form instance, pre-populating it with the test's data
    test_form = TestForm(obj=test)
    test_form.time.data = int(test.time)
    test_form.open_note.data = test.open_note

    if request.method == 'POST':
        # Populate the form with the submitted data
        test_form = TestForm(request.form)
        if test_form.validate_on_submit():
            # Update the test's attributes with form data
            test_form.open_note.data = bool(int(test_form.open_note.data))
            test_form.populate_obj(test)
            db.session.commit()
            flash(f'{test.name} updated successfully!', 'success')
            return redirect(url_for('teacher.get_tests'))
        else:
            flash('Something went wrong, please try again.')
    
    # Creating the student form
    student_form = StudentTestForm()
    # Render the edit form template
    return render_template('teacher/edit_test.html', test_form=test_form, student_form=student_form, test=test, students=enrolled_students)

@bp.route('/delete/<int:test_id>')
def delete_test(test_id):
    TEACHER = db.session.query(Teacher).where(Teacher.id == 1).first()
    test = db.session.query(Test).filter(Test.id == test_id).first()
    if not test:
        return "Test not found", 404

    db.session.delete(test)
    db.session.commit()
    return redirect(url_for('teacher.get_tests'))


@bp.route('/add_student/<int:test_id>', methods=['POST'])
def add_student(test_id):
    TEACHER = db.session.query(Teacher).where(Teacher.id == 1).first()
    test = db.session.query(Test).filter(Test.id == test_id).first()
    if not test:
        return "Test not found", 404
    if request.method == 'POST':
        form = StudentTestForm()
        if form.validate_on_submit():
            student_id = form.student_id.data
            date = form.date.data
            time = form.time.data
            comments = form.comments.data
            date_and_time = datetime.datetime.combine(date, time)
            student = db.session.query(Student).filter(Student.id == student_id).first()
            if not student:
                flash('Student not found', 'error')
                return redirect(url_for('teacher.edit_test', test_id=test_id))
            # Check if the student is already enrolled in the test
            existing_enrollment = db.session.query(StudentTest).filter(
                StudentTest.student_id == student_id,
                StudentTest.test_id == test_id
            ).first()
            if existing_enrollment:
                flash('Student is already enrolled in this test', 'error')
                # return redirect(url_for('teacher.edit_test', test_id=test_id))
                return redirect(url_for('teacher.edit_test', test_id=test_id))
                        
            student_test = StudentTest(
                student=student,
                test=test,
                date=date_and_time,
                comments=comments,
            )
            db.session.add(student_test)
            db.session.commit()
            flash(f'{student.first_name} {student.surname} added successfully to {test.name}', 'success')
            return redirect(url_for('teacher.edit_test', test_id=test_id))

        return redirect(url_for('teacher.edit_test', test_id=test_id))

@bp.route('/remove_student/<int:student_test_id>')
def remove_student(student_test_id: int):
    TEACHER = db.session.query(Teacher).where(Teacher.id == 1).first()
    student_test = db.session.query(StudentTest).filter(StudentTest.id == student_test_id).first()
    if not student_test:
        flash("Student Test not found", 'error')
        return redirect(url_for('teacher.get_tests'))
    
    student = student_test.student
    test = student_test.test

    db.session.delete(student_test)
    db.session.commit()

    flash(f"{student.first_name} removed successfully from {test.name}", 'success')
    return redirect(url_for('teacher.edit_test', test_id=test.id))


@bp.route('/get_students', methods=['GET'])
def get_students():
    TEACHER = db.session.query(Teacher).where(Teacher.id == 1).first()
    students = db.session.query(Student).all()
    s = {}
    for student in students:
        s[f'{student.first_name} {student.surname}'] = student.id
    
    return s

app/templates/teacher/create_test.html
{% extends 'base.html' %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='teacher/edit_test.css') }}">
{% endblock %}

{% block title %}Create Test{% endblock %}

{% block content %}
    <h1>Create Test</h1>
    {# Display flashed messages #}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class="flashed-messages">
                {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    <form method="post" style="margin-top: 1.5rem;">
        {{ form.hidden_tag() }}

        {{ form.name.label }} 
        {{ form.name(size=32) }}

        {{ form.time.label }}
        {{ form.time() }}

        {{ form.open_note.label }}
        {{ form.open_note() }}

        {{ form.comments.label }} 
        {{ form.comments(rows=3, cols=40) }}
        <div class="button-group">
            <a href="{{ url_for('teacher.get_tests') }}" class="button return-btn">Go back</a>
            <button id="finalize-test" type="submit">Create Test</button>
        </div>
    </form>
    
{% endblock %}

app/templates/teacher/edit_test.html
{% extends 'base.html' %}

{% block title %}Edit {{ test.name }}{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='teacher/edit_test.css') }}">
{% endblock %}

{% block content %}
    <div class="section">
        <h1 class="margin-bottom: 1.5rem;">{{ test.name|title }}</h1>
        {# Display flashed messages #}
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <ul class="flashed-messages">
                    {% for category, message in messages %}
                        <li class="{{ category }}">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}


        <div style="margin-bottom: 2rem;">
            <h2>Students Scheduled</h2>
            <div id="selected-students" class="selected-students">
                <table id="assignment-table">
                    <thead>
                        <th>Student</th>
                        <th>Date</th>
                        <th>Time</th>
                        <th></th>
                    </thead>
                    <tbody>
                        {% for student in students %}
                            <tr>
                                <td class="student-name">{{ student.student.first_name + ' ' + student.student.surname }}</td>
                                <td>{{ student.date.date().strftime('%m/%d/%Y') }}</td>
                                <td>{{ student.date.time().strftime('%I:%M') }}</td>
                                <td>
                                    <a href="{{ url_for('teacher.remove_student', student_test_id=student.id) }}" class="remove-student-btn">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-trash" viewBox="0 0 16 16">
                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                        </svg>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <h3 style="margin-top: 2rem">Add a Student</h3>
            <form method="post" id="add-student-form" style="margin-top: 1rem;">
                {{ student_form.hidden_tag() }}
                <!-- Student ID Field -->
                <div class="section">
                    <label for="student-search">Student Name</label>
                    <input name="student-search" type="text" id="student-search" placeholder="Search Bar" autocomplete="off" />
                    <ul id="autocomplete-list" class="autocomplete-list"></ul>
                    </div>
                  
            
                <!-- Date Field -->
                <div class="add-student-group">
                    {{ student_form.date.label }}
                    {{ student_form.date }}
                </div>
                <!-- Time Field -->
                <div class="add-student-group">
                    {{ student_form.time.label }}
                    {{ student_form.time }}
                </div>
            
                <!-- Comments Field -->
                <div class="add-student-group">
                    {{ student_form.comments.label }}
                    {{ student_form.comments }}
                </div>
                <div class="button-group">
                    <a href="{{ url_for('teacher.get_tests') }}" class="button return-btn">Go back</a>
                    <button id="finalize-test-btn" type="submit">Add Student</button>
                </div>
            </form>
        </div>

        <h2>Edit {{ test.name|title }}</h2>
        <form method="POST">
            {{ test_form.hidden_tag() }}

            {{ test_form.name.label }}
            {{ test_form.name(size=20) }}

            {{ test_form.time.label }}
            {{ test_form.time() }}

            {{ test_form.open_note.label }}
            {{ test_form.open_note() }}

            {{ test_form.comments.label }}
            {{ test_form.comments(rows=3, cols=40) }}
            <div class="button-group">
                <button id="finalize-test-btn" type="submit">Update Test</button>
            </div>
        </form>
    </div>
    <script src="{{ url_for('static', filename='teacher/search.js') }}"></script>
{% endblock %}

app/templates/teacher/tests.html
{% extends 'base.html' %}

{% block title %}My Tests{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='teacher/view_tests.css') }}">
{% endblock %}

{% block content %}
        <!-- Create Test Section -->
        <div class="section">
            <h1>My Tests</h1>
            {# Display flashed messages #}
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <ul class="flashed-messages">
                        {% for category, message in messages %}
                            <li class="{{ category }}">{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
                <table style="margin-top: 1.5rem; margin-bottom: 1.5rem">
                    <thead>
                        <th>Test Name</th>
                        <th>Duration</th>
                        <th>Open Note</th>
                        <th></th>
                        <th></th>
                    </thead>
                    <tbody>
                        {% for test in tests %}
                            <tr>
                                <td>{{ test.name.capitalize() }}</td>
                                <td>{{ test.time|int }} min</td>
                                {% if test.open_note %}
                                    <td>Yes</td>
                                {% else %}
                                    <td>No</td>
                                {% endif %}
                                <td>
                                    <a class="edit-btn" href="{{ url_for('teacher.edit_test', test_id=test.id) }}">Edit</a>
                                </td>
                                <td>
                                    <a href="{{ url_for('teacher.delete_test', test_id=test.id) }}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-trash" viewBox="0 0 16 16">
                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                          </svg>
                                    </a>
                                    
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            <div class="button-group">
            <a href="{{ url_for('teacher.create_test') }}" class="button" id="create-test">Create</a>
            </div>
        </div>
{% endblock %}