app/blueprints/test_centre.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from sqlalchemy import asc
from collections import defaultdict
from datetime import datetime, timedelta
from ..db.models import Teacher, Test, StudentTest
from ..utils import get_friday_of_week
from ..app import db

bp = Blueprint('test_centre', __name__, url_prefix='/test_centre')


@bp.route('/')
def view_schedule():
    TEACHER = db.session.query(Teacher).where(Teacher.id == 2).first()
    # checking if they have permission to access the page
    if not TEACHER.test_centre_employee:
        return "You do not have permission to access this page", 403
    
    now = datetime.now().date()
    friday = get_friday_of_week()
    # Get the tests that are there for the rest of the week
    tests = db.session.query(StudentTest).filter(
        StudentTest.date >= now,
        StudentTest.date <= friday,
    ).order_by(StudentTest.date).all()

    is_empty = len(tests) == 0

    # print(tests[0].student.first_name)
    #######
    # Create a dictionary to group tests by day of the week, month, and day of the month
    tests_by_day = defaultdict(list)

    for test in tests:
        # Format the key as "{day of the week}, {month} {day of month}"
        test_date = test.date  # Assuming `test.date` is a datetime.date object
        key = test_date.strftime("%A, %B %d")  # Example: "Monday, October 09"
        tests_by_day[key].append(test)

    # Convert defaultdict to a regular dictionary (optional)
    tests_by_day = dict(tests_by_day)
    ######

    overdue_tests = db.session.query(StudentTest).filter(
        StudentTest.date < now,
        StudentTest.completed == False
    ).all()


    # These are for displaying on the UI
    day_dict = {
        0: "Monday",
        1: "Tuesday",
        2: "Wednesday",
        3: "Thursday",
        4: "Friday",
        5: "Saturday",
        6: "Sunday"
    }

    yes_no = {
        True: 'Yes',
        False: 'No',
    }
    
    return render_template('test_centre/view_schedule.html', 
                           day_dict=day_dict, 
                           yes_no=yes_no,
                           tests_by_day=tests_by_day,
                           overdue_tests=overdue_tests,
                           is_empty=is_empty)


@bp.route('view_student_test/<int:student_test_id>')
def view_student_test(student_test_id: int):
    TEACHER = db.session.query(Teacher).where(Teacher.id == 2).first()
    # checking if they have permission to access the page
    if not TEACHER.test_centre_employee:
        return "You do not have permission to access this page", 403
    
    # Get the test
    student_test = db.session.query(StudentTest).where(StudentTest.id == student_test_id).first()
    if not student_test:
        flash("Student test not found", 'error')
        return redirect(url_for('test_centre.view_schedule'))
    student = student_test.student
    yes_no = {
        True: "Yes",
        False: "No"
    }
    student_info = {
        'Full Name': student.first_name + " " + student.surname,
        'Room': yes_no[student.room],
        'Computer': yes_no[student.computer],
        'AP Additional Support': student.AP_additional_support,
        'AP Additional Strategies': student.AP_additional_strategies,
        'Overview': student.overview,
        'ELL IB Approved': yes_no[student.ELL_IB_approved],
        'Dictionary': yes_no[student.dictionary],
        'ELL Additional Notes': student.ELL_additional_notes,
        'ELL Extra Time': f'{int(student.ELL_extra_time * 100)}%',
        'AP Extra Time': f'{int(student.extra_time * 100)}%',
        # 'total_time': student_test.test.time + student.extra_time * student_test.test.time + student.ell_extra_time * student_test.test.time,

    }

    test = student_test.test
    test_info = {
        'Name': test.name,
        'Date': f'{student_test.date.date()} at {student_test.date.time()}',
        'Duration (minutes)': test.time + test.time * student.extra_time + test.time * student.ELL_extra_time,
        'Open Note': yes_no[test.open_note],
        'Test Comments': test.comments,
        'Student Comments': student_test.comments,
        'Delivered': student_test.delivered,
        'Teacher': test.teacher.name,
    }


    return render_template('test_centre/view_student_test.html', 
                           student_test=student_test,
                           student_info=student_info,
                           test_info=test_info
                           )

app/templates/test_centre/view_schedule.html
{% extends 'base.html' %}

{% block title %}View Tests{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='test_centre/view_schedule.css') }}">
{% endblock %}


{% block content %}
<h1>View Tests for this Week</h1>

    {% if overdue_tests %}
        <h2 style="color: red;">Overdue Tests</h2>
        <table>
            <thead>
                <tr>
                    <th>Student</th>
                    <th>Test Name</th>
                    <th>Date Scheduled</th>
                    <th>Time</th>
                    <th>Delivered</th>
                </tr>
            </thead>
            <tbody>
                {% for test in overdue_tests %}
                    <tr>
                        <td>
                            {{ test.student.first_name + ' ' + test.student.surname }}
                        </td>
                        <td>{{ test.test.name }}</td>
                        <td>{{ day_dict[test.date.date().weekday()] + ', ' + test.date.date().strftime('%m/%d/%Y') }}</td>
                        <td>{{ test.date.time().strftime('%I:%M') }}</td>
                        <td>{{ yes_no[test.delivered] }}</td>
                        <td>
                            <a class="edit-btn" href="{{ url_for('test_centre.view_student_test', student_test_id=test.id) }}">View</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
    {% if not is_empty %}
        {% for header, tests in tests_by_day.items() %}
            <h2>{{ header }}</h2>
            <table>
                <thead>
                    <tr>
                        <th>Student</th>
                        <th>Test Name</th>
                        <th>Time</th>
                        <th>Completed</th>
                        <th>Delivered</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for test in tests %}
                        <tr>
                            <td>
                                {#<a href="{{ url_for('test_centre.view_student_test', student_test_id=test.id) }}">
                                    {{ test.student.first_name + ' ' + test.student.surname }}
                                </a>#}
                                {{ test.student.first_name + ' ' + test.student.surname }}
                            </td>
                            <td>{{ test.test.name }}</td>
                            <td>{{ test.date.time().strftime('%I:%M') }}</td>
                            <td>{{ yes_no[test.completed] }}</td>
                            <td>{{ yes_no[test.delivered] }}</td>
                            <td>
                                <a class="edit-btn" href="{{ url_for('test_centre.view_student_test', student_test_id=test.id) }}">View</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endfor %}
    {% else %}
            <h3>No Tests this Week!</h3>
    {% endif %}
{% endblock %}

app/templates/test_centre/view_student_test.html
{% extends 'base.html' %}

{% block title %}View Student Test{% endblock %}

{% block styles %}
	<link rel="stylesheet" href="{{ url_for('static', filename='test_centre/view_student_test.css') }}">
{% endblock %}

{% block content %}
<h1>View {{ student_test.student.first_name + ' ' + student_test.student.surname }}'s Test</h1>

<h2>Information about {{ student_test.student.preferred }}</h2>
<table border="1" style="width: 5rem;">
	<thead>
		<tr>
			{% for key in student_info.keys() %}
				<th class="lg-th">{{ key }}</th>
			{% endfor %}
		</tr>
	</thead>
	<tbody>
		<tr>
			{% for value in student_info.values() %}
				<td >{{ value }}</td>
			{% endfor %}
		</tr>
	</tbody>
</table>

<h2>Test Information</h2>
<table border="1">
	<thead>
		<tr>
			{% for key in test_info.keys() %}
				<th>{{ key }}</th>
			{% endfor %}
		</tr>
	</thead>
	<tbody>
		<tr>
			{% for value in test_info.values() %}
				<td>{{ value }}</td>
			{% endfor %}
		</tr>
	</tbody>
</table>



<div class="button-group" style="padding-top: 1.2rem;">
	<a class="button return-btn" href="{{ url_for('test_centre.view_schedule') }}">
		Go back to schedule
	</a>
</div>

{% endblock %}